document.writeln("<script type=\"text/javascript\"> ");
document.writeln("  ( function() {");
document.writeln("    if (window.CHITIKA === undefined) {");
document.writeln("      window.CHITIKA = { 'units' : [] };");
document.writeln("    };");
document.writeln("    var unit = {");
document.writeln("      'publisher' : \"freesion\",");
document.writeln("      'width' : 728,");
document.writeln("      'height' : 90,");
document.writeln("      'type' : \"mpu\",");
document.writeln("      'sid' : \"programdevelop\",");
document.writeln("      'color_site_link' : \"0AAAFD\",");
document.writeln("      'color_title' : \"0AAAFD\",");
document.writeln("      'color_border' : \"FFFFFF\",");
document.writeln("      'color_text' : \"000000\",");
document.writeln("      'color_bg' : \"FFFFFF\"");
document.writeln("    };");
document.writeln("    var placement_id = window.CHITIKA.units.length;");
document.writeln("    window.CHITIKA.units.push(unit);");
document.writeln("    document.write('<div id=\"chitikaAdBlock-' + placement_id + '\"></div>');");
document.writeln("    var s = document.createElement('script');");
document.writeln("    s.type = 'text/javascript';");
document.writeln("    s.src = 'http://scripts.chitika.net/getads.js';");
document.writeln("    try {");
document.writeln("      document.getElementsByTagName('head')[0].appendChild(s);");
document.writeln("    } catch(e) {");
document.writeln("      document.write(s.outerHTML);");
document.writeln("    }");
document.writeln("}());");
document.writeln("</script>");
